[[libwasmer]]
arch = "x86_64"
git-tree-sha1 = "a6ec8562ef26fa40fb03ba8d6cdba4e500ba6d64"
os = "macos"

    [[libwasmer.download]]
    sha256 = "861943336007d5a8e9d70fb3ef85cf6995f41654c03dd510e77d1b02a32398f2"
    url = "https://github.com/wasmerio/wasmer/releases/download/v3.0.0-rc.2/wasmer-darwin-amd64.tar.gz"
[[libwasmer]]
arch = "aarch64"
git-tree-sha1 = "5b3f2f7ce7662ae212aae9cbef64cf6138a1bb51"
os = "macos"

    [[libwasmer.download]]
    sha256 = "609e6d07c1871c1937bc4244be6f44d3417b748c334a6ec29d69e0e73b660e89"
    url = "https://github.com/wasmerio/wasmer/releases/download/v3.0.0-rc.2/wasmer-darwin-arm64.tar.gz"
[[libwasmer]]
arch = "x86_64"
git-tree-sha1 = "5cf6910800beb330aa0ea3dd679ef6e9ed864247"
libc = "glibc"
os = "linux"

    [[libwasmer.download]]
    sha256 = "727854f356b145d0a712a0914e7f95e535abcff83410bbe0097f7b0a3dfef9f2"
    url = "https://github.com/wasmerio/wasmer/releases/download/v3.0.0-rc.2/wasmer-linux-amd64.tar.gz"
[[libwasmer]]
arch = "x86_64"
git-tree-sha1 = "4045a26ea3ab0744e4f2ee719d4aba7a88587c38"
libc = "musl"
os = "linux"

    [[libwasmer.download]]
    sha256 = "82cb8a3893a57d70b17fe43e9910903aa9f85bce75ec2c6c4b7a31702865fe11"
    url = "https://github.com/wasmerio/wasmer/releases/download/v3.0.0-rc.2/wasmer-linux-musl-amd64.tar.gz"
